# Generated by Django 4.1.2 on 2022-10-24 20:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('p', 'Pendiente'), ('pr', 'En progreso'), ('f', 'Finalizado'), ('c', 'Cancelado')], max_length=20)),
                ('bookingDate', models.DateField(default=django.utils.timezone.now)),
                ('price', models.FloatField(default=0)),
                ('outstanding', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docId', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour', models.CharField(max_length=30)),
                ('nDays', models.IntegerField(default=1)),
                ('price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docId', models.CharField(max_length=20)),
                ('fNames', models.CharField(max_length=50)),
                ('lNames', models.CharField(max_length=50)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('birth', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TravelerRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.booking')),
                ('travelerId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bookings.traveler')),
            ],
        ),
        migrations.CreateModel(
            name='TourRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.booking')),
                ('tourId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bookings.tour')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='contactId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.contact'),
        ),
    ]
