# Generated by Django 4.1.2 on 2022-11-07 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_tourregistry_bookingid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourregistry',
            name='bookingId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingregs', to='bookings.booking'),
        ),
    ]
